### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by wmfairuz** [holdfenytolvaj/org.ucdetector.ofbiz#1]
Hi,

I don't managed to install this plugin on eclipse Kepler (Debian Linux machine).
Some of the methods I follow to install:

1) Put in dropins then restart using -clean
2) Put in dropins/plugins  then restart using -clean
3) Put in plugins  then restart using -clean
4) Add new software -> Add -> Archive. This one gives me errors.

**Comment by wmfairuz** [comment]
Issue solved by installing UC Detector from the Marketplace first.

**Comment by holdfenytolvaj** [comment]
Yup you need both jars, I've added to the readme.
(It was a zip previously)
