### ISSUE TITLE
Security Vulnerabilities found: Unused Code aka Dead Code

### ISSUE THREAD

**Issue by svavantsa** [holdfenytolvaj/org.ucdetector.ofbiz#2]
We scanned this with HPE Fortify for security vulnerabilities. Out of a total of 400+ different security vulnerabilities, it was ironical to find 13 of them on "Dead Code" (defined as code written but not used) in this plug-in. Any plans to fix it?

**Comment by holdfenytolvaj** [comment]
Hi, 
I would be curious about the list, I might could fix one or two. Although I highly suspect that the dead code might be false positive, at least most.
But I don't use opentaps for maybe 3 years already. So if anybody wants to overtake I would be happy.

**Comment by svavantsa** [comment]
Here is the list.

[UCDetector-OWASTTOP102013Report.xlsx](https://github.com/holdfenytolvaj/org.ucdetector.ofbiz/files/967917/UCDetector-OWASTTOP102013Report.xlsx)

**Comment by holdfenytolvaj** [comment]
Hi, thanks for sending it, though this is not much related with this project.
If I see it correctly these are all for the original UCD which Im just extending. 
This file should be sent to that project http://www.ucdetector.org,

**Comment by svavantsa** [comment]
Well...at this time, I would leave it to you to decide, if you want to fix the code that you adopted before extending, or just pass the buck over. Having said, this, with 400+ security vulnerabilities, including dead code in a tool that is supposed to prevent dead code, we have decided not to recommend this tool at the US Government.

In the future, if you decide to fix them, we may reevaluate the situation and go from there.

Thank you for your efforts to develop a tool and help the world out there.
